import FleetDistance from '@zeliot/common/static/svg/analytics/fleet-analytics/fleet-distance.svg'
import RunningTime from '@zeliot/common/static/svg/analytics/fleet-analytics/running-time.svg'
import IdlingTime from '@zeliot/common/static/svg/analytics/fleet-analytics/idling-time.svg'
import HaltTime from '@zeliot/common/static/svg/analytics/fleet-analytics/halt-time.svg'
import IdleRunRatio from '@zeliot/common/static/svg/analytics/fleet-analytics/idle-run-ratio.svg'
import HaltRunRatio from '@zeliot/common/static/svg/analytics/fleet-analytics/halt-run-ratio.svg'
import FleetUtilization from '@zeliot/common/static/svg/analytics/fleet-analytics/fleet-utilization.svg'
import AverageFleetScore from '@zeliot/common/static/svg/analytics/fleet-analytics/average-fleet-score.svg'
import Penalties from '@zeliot/common/static/svg/analytics/fleet-analytics/penalties.svg'
import NoGPS from '@zeliot/common/static/svg/analytics/fleet-analytics/no-gps.svg'
import Offline from '@zeliot/common/static/svg/analytics/fleet-analytics/offline.svg'
import Running from '@zeliot/common/static/svg/analytics/fleet-analytics/running.svg'
import Groups from '@zeliot/common/static/svg/analytics/fleet-analytics/groups.svg'

import getDurationInHours from '@zeliot/core/base/modules/AnalyticsCards/utils/getDurationInHours'
import { displayTime } from './utils'

const fleetAnalyticsConfig = {
  FLEET_DISTANCE: {
    id: 'FLEET_DISTANCE',
    header: 'Fleet Distance',
    image: FleetDistance,
    value: 'fleetDistance',
    formatValue: value => `${value} kms`,
    showChange: true,
    details: 'TABLE',
    detailsDescription:
      'Shows distance traveled by each vehicle and the relative change in the selected time period',
    hideInTimePeriod: []
  },
  RUNNING_TIME: {
    id: 'RUNNING_TIME',
    header: 'Running Time',
    image: RunningTime,
    value: 'runningTime',
    formatValue: getDurationInHours,
    showChange: true,
    details: 'TABLE',
    detailsDescription: 'Duration of each vehicle in running state',
    hideInTimePeriod: []
  },
  IDLING_TIME: {
    id: 'IDLING_TIME',
    header: 'Idling Time',
    image: IdlingTime,
    value: 'idlingTime',
    formatValue: getDurationInHours,
    showChange: true,
    details: 'TABLE',
    detailsDescription: 'Duration of each vehicle when it was running',
    hideInTimePeriod: []
  },
  HALT_TIME: {
    id: 'HALT_TIME',
    header: 'Halt Time',
    image: HaltTime,
    value: 'haltTime',
    formatValue: getDurationInHours,
    showChange: true,
    details: 'TABLE',
    detailsDescription: 'Duration of each vehicle when it was halted',
    hideInTimePeriod: []
  },
  IDLE_RUN_RATIO: {
    id: 'IDLE_RUN_RATIO',
    header: 'Idle to Run Ratio',
    image: IdleRunRatio,
    value: 'idleToRunRatio',
    showChange: false,
    description: 'Ratio of how long the vehicles were idle compared to running',
    details: null,
    hideInTimePeriod: []
  },
  HALT_RUN_RATIO: {
    id: 'HALT_RUN_RATIO',
    header: 'Halt to Run Ratio',
    image: HaltRunRatio,
    value: 'haltToRunRatio',
    showChange: false,
    description: 'Ratio of how long the vehicles were halt compared to running',
    details: null,
    hideInTimePeriod: []
  },
  FLEET_UTILIZATION: {
    id: 'FLEET_UTILIZATION',
    header: 'Fleet Utilization',
    image: FleetUtilization,
    value: 'fleetUtilization',
    formatValue: value => `${value} %`,
    showChange: false,
    description:
      'A Vehicle is considered utilized if it runs for more than 30 minutes a day',
    details: 'TABLE',
    detailsDescription:
      'A vehicle is considered utilized if it has run for more than 30 minutes in a day',
    hideInTimePeriod: ['ALL_TIME']
  },
  FLEET_SCORE: {
    id: 'FLEET_SCORE',
    header: 'Average Fleet Score',
    image: AverageFleetScore,
    value: 'averageFleetScore',
    showChange: false,
    description: 'Average performance score of the fleet',
    details: 'TABLE',
    detailsDescription:
      'A vehicle is given a performance score(between 0 - 100) based on various factors',
    hideInTimePeriod: []
  },
  PENALTIES: {
    id: 'PENALTIES',
    header: 'Penalties',
    image: Penalties,
    value: 'penalties',
    showChange: false,
    description: 'Number of critical alerts generated by the fleet',
    details: null,
    hideInTimePeriod: []
  },
  MOST_NO_GPS_VEHICLE: {
    id: 'MOST_NO_GPS_VEHICLE',
    header: 'Most No-GPS Vehicle',
    image: NoGPS,
    value: 'mostNoGPSVehicle',
    showChange: false,
    description: 'The vehicle that did not have GPS for the longest time',
    details: 'TABLE',
    detailsDescription:
      'Vehicles and the number of times it went into No GPS state',
    hideInTimePeriod: []
  },
  MOST_OFFLINE_VEHICLE: {
    id: 'MOST_OFFLINE_VEHICLE',
    header: 'Most OFFLINE Vehicle',
    image: Offline,
    value: 'mostOfflineVehicle',
    showChange: false,
    description: 'The vehicle that was offline for the longest time',
    details: 'TABLE',
    detailsDescription: 'Vehicles and the number of times it went offline',
    hideInTimePeriod: []
  },
  MOST_RUNNING_VEHICLE: {
    id: 'MOST_RUNNING_VEHICLE',
    header: 'Most Running Vehicle',
    image: Running,
    value: 'mostRunningVehicle',
    showChange: false,
    description: 'The vehicle that was running for the longest time',
    details: 'TABLE',
    detailsDescription: 'Top 5 vehicles with highest running times',
    hideInTimePeriod: []
  },
  MOST_IDLE_VEHICLE: {
    id: 'MOST_IDLE_VEHICLE',
    header: 'Most Idle Vehicle',
    image: Running,
    value: 'mostIdleVehicle',
    showChange: false,
    description: 'The vehicle that was idle for the longest time',
    details: 'TABLE',
    detailsDescription: 'Top 5 vehicles with highest idling times',
    hideInTimePeriod: []
  },
  MOST_HALTED_VEHICLE: {
    id: 'MOST_HALTED_VEHICLE',
    header: 'Most Halted Vehicle',
    image: Running,
    value: 'mostHaltedVehicle',
    showChange: false,
    description: 'The vehicle that was halted for the longest time',
    details: 'TABLE',
    detailsDescription: 'Top 5 vehicles with highest halt times',
    hideInTimePeriod: []
  },
  TIME_OF_DAY_MOST_RUNNING: {
    id: 'TIME_OF_DAY_MOST_RUNNING',
    header: 'Most Running Hour',
    image: Running,
    value: 'mostRunningTime',
    formatValue: displayTime,
    showChange: false,
    description: 'Time of Day when most vehicles were running',
    details: 'TIME_GRAPH',
    detailsDescription:
      'Shows a graph with average number of vehicles running between each hour of the day over the selected time period(Note: Time is in UTC)',
    hideInTimePeriod: []
  },
  TIME_OF_DAY_MOST_IDLING: {
    id: 'TIME_OF_DAY_MOST_IDLING',
    header: 'Most Idling Hour',
    image: Running,
    value: 'mostIdlingTime',
    formatValue: displayTime,
    showChange: false,
    description: 'Time of Day when most vehicles were idling',
    details: 'TIME_GRAPH',
    detailsDescription:
      'Shows a graph with average number of vehicles idling between each hour of the day over the selected time period(Note: Time is in UTC)',
    hideInTimePeriod: []
  },
  TIME_OF_DAY_MOST_HALTED: {
    id: 'TIME_OF_DAY_MOST_HALTED',
    header: 'Most Halted Hour',
    image: Running,
    value: 'mostHaltedTime',
    formatValue: displayTime,
    showChange: false,
    description: 'Time of Day when most vehicles were halted',
    details: 'TIME_GRAPH',
    detailsDescription:
      'Shows a graph with average number of vehicles halted between each hour of the day over the selected time period(Note: Time is in UTC)',
    hideInTimePeriod: []
  },
  TOTAL_GROUPS: {
    id: 'TOTAL_GROUPS',
    header: 'Total Number of Groups',
    image: Groups,
    value: 'totalNumberOfGroups',
    showChange: false,
    description: 'All the groups created in your fleet',
    details: null,
    hideInTimePeriod: []
  }
}

export default fleetAnalyticsConfig
